"""create courts table

Revision ID: 2faf9368a493
Revises: cb47e51bf075
Create Date: 2026-10-03 12:45:00.052720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2faf9368a493'
down_revision = 'cb47e51bf075'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('sport_type', sa.Enum('TENNIS', 'PADEL', 'BADMINTON', 'BOX_CRICKET', name='sport_types_enum'), nullable=False),
    sa.Column('surface_type', sa.String(length=50), nullable=True),
    sa.Column('is_indoor', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'MAINTENANCE', 'INACTIVE', name='court_status_enum'), nullable=False),
    sa.Column('custom_open_time', sa.String(length=5), nullable=True),
    sa.Column('custom_close_time', sa.String(length=5), nullable=True),
    sa.Column('features', sa.JSON(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('courts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_courts_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_courts_sport_type'), ['sport_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_courts_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_courts_status'))
        batch_op.drop_index(batch_op.f('ix_courts_sport_type'))
        batch_op.drop_index(batch_op.f('ix_courts_name'))

    op.drop_table('courts')
    # ### end Alembic commands ###
