"""create bookings and court occupancies tables

Revision ID: 4066243cfafe
Revises: 2faf9368a493
Create Date: 2026-10-03 12:52:42.431742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4066243cfafe'
down_revision = '2faf9368a493'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('booking_reference', sa.String(length=30), nullable=False),
    sa.Column('court_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('booking_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('CONFIRMED', 'CANCELLED', 'COMPLETED', name='booking_status_enum'), nullable=False),
    sa.Column('is_walk_in', sa.Boolean(), nullable=False),
    sa.Column('is_social_play', sa.Boolean(), nullable=False),
    sa.Column('guest_name', sa.String(length=100), nullable=True),
    sa.Column('guest_phone', sa.String(length=20), nullable=True),
    sa.Column('guest_email', sa.String(length=120), nullable=True),
    sa.Column('base_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('final_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('pricing_breakdown', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['court_id'], ['courts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bookings_booking_date'), ['booking_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_booking_reference'), ['booking_reference'], unique=True)
        batch_op.create_index(batch_op.f('ix_bookings_court_id'), ['court_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_member_id'), ['member_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_start_time'), ['start_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_user_id'), ['user_id'], unique=False)

    op.create_table('court_occupancies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('court_id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('slot_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['court_id'], ['courts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('court_id', 'slot_start', name='uq_court_slot_occupancy')
    )
    with op.batch_alter_table('court_occupancies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_court_occupancies_booking_id'), ['booking_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_court_occupancies_court_id'), ['court_id'], unique=False)
        batch_op.create_index('ix_court_occupancy_court_slot', ['court_id', 'slot_start'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('court_occupancies', schema=None) as batch_op:
        batch_op.drop_index('ix_court_occupancy_court_slot')
        batch_op.drop_index(batch_op.f('ix_court_occupancies_court_id'))
        batch_op.drop_index(batch_op.f('ix_court_occupancies_booking_id'))

    op.drop_table('court_occupancies')
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bookings_user_id'))
        batch_op.drop_index(batch_op.f('ix_bookings_status'))
        batch_op.drop_index(batch_op.f('ix_bookings_start_time'))
        batch_op.drop_index(batch_op.f('ix_bookings_member_id'))
        batch_op.drop_index(batch_op.f('ix_bookings_court_id'))
        batch_op.drop_index(batch_op.f('ix_bookings_booking_reference'))
        batch_op.drop_index(batch_op.f('ix_bookings_booking_date'))

    op.drop_table('bookings')
    # ### end Alembic commands ###
