"""create notifications table

Revision ID: 54b314615cce
Revises: fa27d8e4b14c
Create Date: 2026-10-03 15:29:49.045324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54b314615cce'
down_revision = 'fa27d8e4b14c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('recipient', sa.String(length=255), nullable=False),
    sa.Column('recipient_type', sa.String(length=50), nullable=True),
    sa.Column('recipient_id', sa.Integer(), nullable=True),
    sa.Column('notification_type', sa.Enum('BOOKING_CONFIRMATION', 'MEMBERSHIP_EXPIRY_REMINDER', 'ORDER_NOTIFICATION', 'CRM_FOLLOW_UP_REMINDER', 'LOW_STOCK_ALERT', 'REPORT_GENERATION', 'EXCEL_EXPORT', 'GENERAL', name='notification_type_enum', native_enum=False), nullable=False),
    sa.Column('channel', sa.Enum('LOG', 'IN_APP', 'EMAIL', 'SMS', name='notification_channel_enum', native_enum=False), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.Column('reference_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'FAILED', name='notification_status_enum', native_enum=False), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_notification_type'), ['notification_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_recipient'), ['recipient'], unique=False)
        batch_op.create_index('ix_notifications_ref', ['reference_type', 'reference_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_reference_id'), ['reference_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_reference_type'), ['reference_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_status'), ['status'], unique=False)
        batch_op.create_index('ix_notifications_type_status', ['notification_type', 'status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index('ix_notifications_type_status')
        batch_op.drop_index(batch_op.f('ix_notifications_status'))
        batch_op.drop_index(batch_op.f('ix_notifications_reference_type'))
        batch_op.drop_index(batch_op.f('ix_notifications_reference_id'))
        batch_op.drop_index('ix_notifications_ref')
        batch_op.drop_index(batch_op.f('ix_notifications_recipient'))
        batch_op.drop_index(batch_op.f('ix_notifications_notification_type'))

    op.drop_table('notifications')
    # ### end Alembic commands ###
