"""create payments, audits, and webhook events tables

Revision ID: a24c8b73c931
Revises: 4066243cfafe
Create Date: 2026-10-03 13:50:18.256352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a24c8b73c931'
down_revision = '4066243cfafe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('payment_reference', sa.String(length=30), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('payment_method', sa.Enum('CASH', 'CARD', 'UPI', 'ONLINE', name='payment_method_enum'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PAID', 'FAILED', 'CANCELLED', 'REFUND_PENDING', 'REFUNDED', name='payment_status_enum'), nullable=False),
    sa.Column('item_type', sa.Enum('BOOKING', 'MEMBERSHIP', 'SHOP_ORDER', 'POS_ORDER', 'INVOICE', name='payment_item_type_enum'), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('gateway_order_id', sa.String(length=100), nullable=True),
    sa.Column('gateway_payment_id', sa.String(length=100), nullable=True),
    sa.Column('gateway_refund_id', sa.String(length=100), nullable=True),
    sa.Column('gateway_signature', sa.String(length=255), nullable=True),
    sa.Column('gateway_metadata', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('refunded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_gateway_order_id'), ['gateway_order_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_payments_gateway_payment_id'), ['gateway_payment_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_payments_gateway_refund_id'), ['gateway_refund_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_payments_item_id'), ['item_id'], unique=False)
        batch_op.create_index('ix_payments_item_lookup', ['item_type', 'item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_item_type'), ['item_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_member_id'), ['member_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_payment_method'), ['payment_method'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_payment_reference'), ['payment_reference'], unique=True)
        batch_op.create_index(batch_op.f('ix_payments_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_user_id'), ['user_id'], unique=False)

    op.create_table('payment_audits',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('previous_status', sa.String(length=30), nullable=True),
    sa.Column('new_status', sa.String(length=30), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('actor_type', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('metadata_snapshot', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment_audits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_audits_payment_id'), ['payment_id'], unique=False)

    op.create_table('payment_webhook_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.String(length=100), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=True),
    sa.Column('outcome', sa.String(length=50), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment_webhook_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_webhook_events_event_id'), ['event_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_payment_webhook_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_webhook_events_payment_id'), ['payment_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_webhook_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_webhook_events_payment_id'))
        batch_op.drop_index(batch_op.f('ix_payment_webhook_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_payment_webhook_events_event_id'))

    op.drop_table('payment_webhook_events')
    with op.batch_alter_table('payment_audits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_audits_payment_id'))

    op.drop_table('payment_audits')
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_user_id'))
        batch_op.drop_index(batch_op.f('ix_payments_status'))
        batch_op.drop_index(batch_op.f('ix_payments_payment_reference'))
        batch_op.drop_index(batch_op.f('ix_payments_payment_method'))
        batch_op.drop_index(batch_op.f('ix_payments_member_id'))
        batch_op.drop_index(batch_op.f('ix_payments_item_type'))
        batch_op.drop_index('ix_payments_item_lookup')
        batch_op.drop_index(batch_op.f('ix_payments_item_id'))
        batch_op.drop_index(batch_op.f('ix_payments_gateway_refund_id'))
        batch_op.drop_index(batch_op.f('ix_payments_gateway_payment_id'))
        batch_op.drop_index(batch_op.f('ix_payments_gateway_order_id'))

    op.drop_table('payments')
    # ### end Alembic commands ###
