"""create members and memberships tables

Revision ID: cb47e51bf075
Revises: c19007162ec3
Create Date: 2026-10-03 12:36:38.344422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb47e51bf075'
down_revision = 'c19007162ec3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('membership_plans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('displayed_monthly_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('billing_frequency', sa.String(length=50), nullable=False),
    sa.Column('duration_months', sa.Integer(), nullable=False),
    sa.Column('complimentary_months', sa.Integer(), nullable=False),
    sa.Column('benefits', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('membership_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_membership_plans_code'), ['code'], unique=True)

    op.create_table('members',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('emergency_contact_name', sa.String(length=100), nullable=True),
    sa.Column('emergency_contact_phone', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_members_phone'), ['phone'], unique=False)
        batch_op.create_index(batch_op.f('ix_members_user_id'), ['user_id'], unique=True)

    op.create_table('memberships',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'EXPIRED', 'CANCELLED', 'UPGRADED', 'DOWNGRADED', name='membership_status_enum'), nullable=False),
    sa.Column('price_paid', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['membership_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_memberships_end_date'), ['end_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_memberships_member_id'), ['member_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_memberships_plan_id'), ['plan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_memberships_start_date'), ['start_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_memberships_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_memberships_status'))
        batch_op.drop_index(batch_op.f('ix_memberships_start_date'))
        batch_op.drop_index(batch_op.f('ix_memberships_plan_id'))
        batch_op.drop_index(batch_op.f('ix_memberships_member_id'))
        batch_op.drop_index(batch_op.f('ix_memberships_end_date'))

    op.drop_table('memberships')
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_members_user_id'))
        batch_op.drop_index(batch_op.f('ix_members_phone'))

    op.drop_table('members')
    with op.batch_alter_table('membership_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_membership_plans_code'))

    op.drop_table('membership_plans')
    # ### end Alembic commands ###
