"""create shop_orders and shop_order_items tables

Revision ID: e0b78d198b87
Revises: 3f6bfac947a4
Create Date: 2026-10-03 14:44:07.886522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0b78d198b87'
down_revision = '3f6bfac947a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shop_orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_reference', sa.String(length=30), nullable=False),
    sa.Column('order_type', sa.Enum('COUNTER', 'ONLINE', name='shop_order_type_enum'), nullable=False),
    sa.Column('fulfillment_type', sa.Enum('PICKUP', 'DELIVERY', name='shop_fulfillment_type_enum'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'PROCESSING', 'READY_FOR_PICKUP', 'SHIPPED', 'COMPLETED', 'CANCELLED', name='shop_order_status_enum'), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('customer_name', sa.String(length=100), nullable=False),
    sa.Column('customer_phone', sa.String(length=20), nullable=True),
    sa.Column('customer_email', sa.String(length=255), nullable=True),
    sa.Column('delivery_address', sa.Text(), nullable=True),
    sa.Column('subtotal_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('delivery_fee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_status', sa.String(length=30), nullable=False),
    sa.Column('payment_method', sa.String(length=30), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('discount_amount >= 0', name='ck_shop_orders_discount_non_negative'),
    sa.CheckConstraint('subtotal_amount >= 0', name='ck_shop_orders_subtotal_non_negative'),
    sa.CheckConstraint('total_amount >= 0', name='ck_shop_orders_total_non_negative'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shop_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shop_orders_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_shop_orders_created_by_id'), ['created_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shop_orders_fulfillment_type'), ['fulfillment_type'], unique=False)
        batch_op.create_index('ix_shop_orders_member_created', ['member_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_shop_orders_member_id'), ['member_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shop_orders_order_reference'), ['order_reference'], unique=True)
        batch_op.create_index(batch_op.f('ix_shop_orders_order_type'), ['order_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_shop_orders_status'), ['status'], unique=False)
        batch_op.create_index('ix_shop_orders_status_created', ['status', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_shop_orders_user_id'), ['user_id'], unique=False)

    op.create_table('shop_order_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('product_sku', sa.String(length=50), nullable=False),
    sa.Column('product_name', sa.String(length=200), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cost_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('discount_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.CheckConstraint('discount_pct >= 0', name='ck_shop_order_items_discount_pct_non_negative'),
    sa.CheckConstraint('quantity > 0', name='ck_shop_order_items_quantity_positive'),
    sa.CheckConstraint('total_price >= 0', name='ck_shop_order_items_total_price_non_negative'),
    sa.CheckConstraint('unit_price >= 0', name='ck_shop_order_items_unit_price_non_negative'),
    sa.ForeignKeyConstraint(['order_id'], ['shop_orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shop_order_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shop_order_items_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shop_order_items_product_id'), ['product_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shop_order_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shop_order_items_product_id'))
        batch_op.drop_index(batch_op.f('ix_shop_order_items_order_id'))

    op.drop_table('shop_order_items')
    with op.batch_alter_table('shop_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shop_orders_user_id'))
        batch_op.drop_index('ix_shop_orders_status_created')
        batch_op.drop_index(batch_op.f('ix_shop_orders_status'))
        batch_op.drop_index(batch_op.f('ix_shop_orders_order_type'))
        batch_op.drop_index(batch_op.f('ix_shop_orders_order_reference'))
        batch_op.drop_index(batch_op.f('ix_shop_orders_member_id'))
        batch_op.drop_index('ix_shop_orders_member_created')
        batch_op.drop_index(batch_op.f('ix_shop_orders_fulfillment_type'))
        batch_op.drop_index(batch_op.f('ix_shop_orders_created_by_id'))
        batch_op.drop_index(batch_op.f('ix_shop_orders_created_at'))

    op.drop_table('shop_orders')
    # ### end Alembic commands ###
