"""create pos tables and staff shifts

Revision ID: f021cd84e1a4
Revises: e0b78d198b87
Create Date: 2026-10-03 15:01:32.208288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f021cd84e1a4'
down_revision = 'e0b78d198b87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pos_menu_categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pos_menu_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pos_menu_categories_slug'), ['slug'], unique=True)

    op.create_table('pos_tables',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('table_number', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'OCCUPIED', 'RESERVED', 'OUT_OF_SERVICE', name='tablestatus', native_enum=False), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('capacity > 0', name='check_table_capacity_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pos_tables', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pos_tables_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_pos_tables_table_number'), ['table_number'], unique=True)

    op.create_table('pos_menu_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('preparation_time_minutes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('price >= 0', name='check_pos_menu_item_price_non_negative'),
    sa.CheckConstraint('tax_rate >= 0', name='check_pos_menu_item_tax_non_negative'),
    sa.ForeignKeyConstraint(['category_id'], ['pos_menu_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pos_menu_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pos_menu_items_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pos_menu_items_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_pos_menu_items_name'), ['name'], unique=False)

    op.create_table('pos_shifts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('shift_reference', sa.String(length=30), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'CLOSED', name='shiftstatus', native_enum=False), nullable=False),
    sa.Column('starting_cash', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('ending_cash', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('starting_cash >= 0', name='check_shift_starting_cash_non_negative'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pos_shifts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pos_shifts_shift_reference'), ['shift_reference'], unique=True)
        batch_op.create_index(batch_op.f('ix_pos_shifts_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_pos_shifts_user_id'), ['user_id'], unique=False)

    op.create_table('pos_tabs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tab_reference', sa.String(length=30), nullable=False),
    sa.Column('table_id', sa.Integer(), nullable=False),
    sa.Column('shift_id', sa.Integer(), nullable=False),
    sa.Column('opened_by_user_id', sa.Integer(), nullable=False),
    sa.Column('closed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('customer_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'PAID', 'CLOSED', 'VOIDED', name='tabstatus', native_enum=False), nullable=False),
    sa.Column('subtotal_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('discount_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_status', sa.Enum('UNPAID', 'PARTIALLY_PAID', 'PAID', 'REFUNDED', name='tabpaymentstatus', native_enum=False), nullable=False),
    sa.Column('payment_method', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('void_reason', sa.Text(), nullable=True),
    sa.Column('opened_at', sa.DateTime(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('discount_amount >= 0', name='check_pos_tab_discount_non_negative'),
    sa.CheckConstraint('paid_amount >= 0', name='check_pos_tab_paid_non_negative'),
    sa.CheckConstraint('subtotal_amount >= 0', name='check_pos_tab_subtotal_non_negative'),
    sa.CheckConstraint('tax_amount >= 0', name='check_pos_tab_tax_non_negative'),
    sa.CheckConstraint('total_amount >= 0', name='check_pos_tab_total_non_negative'),
    sa.ForeignKeyConstraint(['closed_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['opened_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['shift_id'], ['pos_shifts.id'], ),
    sa.ForeignKeyConstraint(['table_id'], ['pos_tables.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pos_tabs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pos_tabs_member_id'), ['member_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pos_tabs_opened_by_user_id'), ['opened_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pos_tabs_payment_status'), ['payment_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_pos_tabs_shift_id'), ['shift_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pos_tabs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_pos_tabs_tab_reference'), ['tab_reference'], unique=True)
        batch_op.create_index(batch_op.f('ix_pos_tabs_table_id'), ['table_id'], unique=False)
        batch_op.create_index('uq_pos_open_tab_table', ['table_id'], unique=True, sqlite_where=sa.text("status = 'OPEN'"), postgresql_where=sa.text("status = 'OPEN'"))

    op.create_table('pos_order_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tab_id', sa.Integer(), nullable=False),
    sa.Column('menu_item_id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=100), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('discount_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('subtotal_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('kitchen_status', sa.Enum('PENDING', 'QUEUED', 'PREPARING', 'READY', 'SERVED', 'CANCELLED', name='kitchenstatus', native_enum=False), nullable=False),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('sent_to_kitchen_at', sa.DateTime(), nullable=True),
    sa.Column('prepared_at', sa.DateTime(), nullable=True),
    sa.Column('served_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('quantity > 0', name='check_pos_order_item_quantity_positive'),
    sa.CheckConstraint('subtotal_amount >= 0', name='check_pos_order_item_subtotal_non_negative'),
    sa.CheckConstraint('total_amount >= 0', name='check_pos_order_item_total_non_negative'),
    sa.CheckConstraint('unit_price >= 0', name='check_pos_order_item_price_non_negative'),
    sa.ForeignKeyConstraint(['menu_item_id'], ['pos_menu_items.id'], ),
    sa.ForeignKeyConstraint(['tab_id'], ['pos_tabs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pos_order_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pos_order_items_kitchen_status'), ['kitchen_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_pos_order_items_menu_item_id'), ['menu_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pos_order_items_tab_id'), ['tab_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pos_order_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pos_order_items_tab_id'))
        batch_op.drop_index(batch_op.f('ix_pos_order_items_menu_item_id'))
        batch_op.drop_index(batch_op.f('ix_pos_order_items_kitchen_status'))

    op.drop_table('pos_order_items')
    with op.batch_alter_table('pos_tabs', schema=None) as batch_op:
        batch_op.drop_index('uq_pos_open_tab_table', sqlite_where=sa.text("status = 'OPEN'"), postgresql_where=sa.text("status = 'OPEN'"))
        batch_op.drop_index(batch_op.f('ix_pos_tabs_table_id'))
        batch_op.drop_index(batch_op.f('ix_pos_tabs_tab_reference'))
        batch_op.drop_index(batch_op.f('ix_pos_tabs_status'))
        batch_op.drop_index(batch_op.f('ix_pos_tabs_shift_id'))
        batch_op.drop_index(batch_op.f('ix_pos_tabs_payment_status'))
        batch_op.drop_index(batch_op.f('ix_pos_tabs_opened_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_pos_tabs_member_id'))

    op.drop_table('pos_tabs')
    with op.batch_alter_table('pos_shifts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pos_shifts_user_id'))
        batch_op.drop_index(batch_op.f('ix_pos_shifts_status'))
        batch_op.drop_index(batch_op.f('ix_pos_shifts_shift_reference'))

    op.drop_table('pos_shifts')
    with op.batch_alter_table('pos_menu_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pos_menu_items_name'))
        batch_op.drop_index(batch_op.f('ix_pos_menu_items_code'))
        batch_op.drop_index(batch_op.f('ix_pos_menu_items_category_id'))

    op.drop_table('pos_menu_items')
    with op.batch_alter_table('pos_tables', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pos_tables_table_number'))
        batch_op.drop_index(batch_op.f('ix_pos_tables_status'))

    op.drop_table('pos_tables')
    with op.batch_alter_table('pos_menu_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pos_menu_categories_slug'))

    op.drop_table('pos_menu_categories')
    # ### end Alembic commands ###
