"""create crm leads follow_ups notes trials and quotes

Revision ID: fa27d8e4b14c
Revises: f021cd84e1a4
Create Date: 2026-10-03 15:11:23.544305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa27d8e4b14c'
down_revision = 'f021cd84e1a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crm_leads',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lead_reference', sa.String(length=30), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('source', sa.Enum('WEBSITE', 'WALK_IN', 'PHONE', 'REFERRAL', 'SOCIAL_MEDIA', 'EVENT', 'OTHER', name='leadsource', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'CONTACTED', 'QUALIFIED', 'TRIAL_SCHEDULED', 'TRIAL_COMPLETED', 'PROPOSAL_SENT', 'CONVERTED', 'LOST', name='leadstatus', native_enum=False), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='leadpriority', native_enum=False), nullable=False),
    sa.Column('preferred_sport', sa.String(length=50), nullable=True),
    sa.Column('interested_plan', sa.String(length=50), nullable=True),
    sa.Column('initial_message', sa.Text(), nullable=True),
    sa.Column('assigned_staff_id', sa.Integer(), nullable=True),
    sa.Column('converted_member_id', sa.Integer(), nullable=True),
    sa.Column('converted_at', sa.DateTime(), nullable=True),
    sa.Column('lost_reason', sa.Text(), nullable=True),
    sa.Column('lost_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_staff_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['converted_member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('crm_leads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crm_leads_converted_member_id'), ['converted_member_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_leads_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_leads_lead_reference'), ['lead_reference'], unique=True)
        batch_op.create_index(batch_op.f('ix_crm_leads_phone'), ['phone'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_leads_status'), ['status'], unique=False)

    op.create_table('crm_follow_ups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('assigned_staff_id', sa.Integer(), nullable=True),
    sa.Column('follow_up_type', sa.Enum('CALL', 'EMAIL', 'MEETING', 'MESSAGE', 'TOUR', 'OTHER', name='followuptype', native_enum=False), nullable=False),
    sa.Column('scheduled_date', sa.DateTime(), nullable=False),
    sa.Column('completed_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'CANCELLED', name='followupstatus', native_enum=False), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('outcome', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_staff_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['crm_leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('crm_follow_ups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crm_follow_ups_lead_id'), ['lead_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_follow_ups_scheduled_date'), ['scheduled_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_follow_ups_status'), ['status'], unique=False)

    op.create_table('crm_notes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('staff_user_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['crm_leads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['staff_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('crm_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crm_notes_lead_id'), ['lead_id'], unique=False)

    op.create_table('crm_quotes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('quote_reference', sa.String(length=30), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('plan_code', sa.String(length=30), nullable=True),
    sa.Column('plan_name', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('final_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SENT', 'ACCEPTED', 'REJECTED', 'EXPIRED', name='quotestatus', native_enum=False), nullable=False),
    sa.Column('valid_until', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('amount >= 0', name='check_crm_quote_amount_non_negative'),
    sa.CheckConstraint('discount_amount >= 0', name='check_crm_quote_discount_non_negative'),
    sa.CheckConstraint('final_amount >= 0', name='check_crm_quote_final_amount_non_negative'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['crm_leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('crm_quotes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crm_quotes_lead_id'), ['lead_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_quotes_quote_reference'), ['quote_reference'], unique=True)
        batch_op.create_index(batch_op.f('ix_crm_quotes_status'), ['status'], unique=False)

    op.create_table('crm_trial_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('preferred_date', sa.Date(), nullable=False),
    sa.Column('preferred_time_slot', sa.String(length=50), nullable=False),
    sa.Column('sport', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('REQUESTED', 'CONFIRMED', 'COMPLETED', 'CANCELLED', 'NO_SHOW', name='trialstatus', native_enum=False), nullable=False),
    sa.Column('confirmed_datetime', sa.DateTime(), nullable=True),
    sa.Column('court_id', sa.Integer(), nullable=True),
    sa.Column('coach_user_id', sa.Integer(), nullable=True),
    sa.Column('staff_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['coach_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['court_id'], ['courts.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['crm_leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('crm_trial_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crm_trial_sessions_lead_id'), ['lead_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_trial_sessions_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crm_trial_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crm_trial_sessions_status'))
        batch_op.drop_index(batch_op.f('ix_crm_trial_sessions_lead_id'))

    op.drop_table('crm_trial_sessions')
    with op.batch_alter_table('crm_quotes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crm_quotes_status'))
        batch_op.drop_index(batch_op.f('ix_crm_quotes_quote_reference'))
        batch_op.drop_index(batch_op.f('ix_crm_quotes_lead_id'))

    op.drop_table('crm_quotes')
    with op.batch_alter_table('crm_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crm_notes_lead_id'))

    op.drop_table('crm_notes')
    with op.batch_alter_table('crm_follow_ups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crm_follow_ups_status'))
        batch_op.drop_index(batch_op.f('ix_crm_follow_ups_scheduled_date'))
        batch_op.drop_index(batch_op.f('ix_crm_follow_ups_lead_id'))

    op.drop_table('crm_follow_ups')
    with op.batch_alter_table('crm_leads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crm_leads_status'))
        batch_op.drop_index(batch_op.f('ix_crm_leads_phone'))
        batch_op.drop_index(batch_op.f('ix_crm_leads_lead_reference'))
        batch_op.drop_index(batch_op.f('ix_crm_leads_email'))
        batch_op.drop_index(batch_op.f('ix_crm_leads_converted_member_id'))

    op.drop_table('crm_leads')
    # ### end Alembic commands ###
